{% set name = "languagetool-rust" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeertmans/languagetool-rust/archive/v{{ version }}.tar.gz
  sha256: 8fbd18fd9b6a7e049fec39d9d4ebcc3563ab7779b849ad5aa2df1d737002c30a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - ltrs --help

about:
  home: https://github.com/jeertmans/languagetool-rust
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: LanguageTool API in Rust
  dev_url: https://github.com/jeertmans/languagetool-rust

extra:
  recipe-maintainers:
    - danielnachun
