context:
  version: "3.0.1"

package:
  name: languagetool-rust
  version: ${{ version }}

source:
  url: https://github.com/jeertmans/languagetool-rust/archive/v${{ version }}.tar.gz
  sha256: fc3dfcb73f21c58bb143b5f31495892755bc1e945aa64f522f3640e1cf77de31

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - ltrs --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: LanguageTool API in Rust
  homepage: https://github.com/jeertmans/languagetool-rust
  repository: https://github.com/jeertmans/languagetool-rust

extra:
  recipe-maintainers:
    - danielnachun
